### PR TITLE
Site is now working with Jekyll 3.8

### PR DESCRIPTION
**Pull request by Kyrremann**

### CODE REVIEW

**Comment by Kyrremann** [comment]
@ssorallen I fixed the issue of mixed branches.

**Comment by ssorallen** [comment]
Thanks for the reminder. This looks good, except I see this warning when I start Jekyll:

```
        Pagination: Disabled in site.config.
                    done in 0.934 seconds.
```

Have you tested that pagination works properly?

**Comment by Kyrremann** [comment]
Hum, good point. I'll take a look after work tonight.

**Comment by Kyrremann** [comment]
One question, do you want the page to work with github-pages?

There is one pagnation plugin that works with github-pages, the official one, but it's not under active development any more (https://github.com/jekyll/jekyll-paginate). 
The one that is still under development is not supported with github-pages. Also `highlighter: pygments` is not working either with github-pages.

**Comment by ssorallen** [comment]
Do you mean working with deploying to GitHub Pages? That would be ideal. What wouldn't work with Github Pages?

**Comment by Kyrremann** [comment]
Deploying to github-pages without pre-compiling the site. Cause then we also need to remove/change the `pygments.rb` plugin too, as it's not supported.

I'll just get the pagnation working first, then I'll fix the other one too :)

**Comment by Kyrremann** [comment]
I think we can just use the default highlighter in jekyll 3
https://jekyllrb.com/docs/liquid/tags/#code-snippet-highlighting

**Comment by ssorallen** [comment]
Oh! You should definitely have to compile before pushing to a `gh-pages` branch. GitHub Pages is a fully static host, there's nothing dynamic to run.

**Comment by ssorallen** [comment]
The configuration of this repository/project might be misleading. It doesn't have a `master` branch, but I'm not sure that's the best pattern to follow. Having a separate `master` and `gh-pages` means `gh-pages` holds the compiled code.

**Comment by Kyrremann** [comment]
I think that is the old github-pages, I've set up two pages in the last month, and neither of them has the `_site` catalogue or `gb-pages` branch.
See https://github.com/Kyrremann/kyrremann.github.io which is based of yours, and https://github.com/Kyrremann/tingtartid.

**Comment by Kyrremann** [comment]
I think this one answers what I know: https://stackoverflow.com/a/31871892/502493

**Comment by Kyrremann** [comment]
Okay, it's now up and running on my account. As there is not 11 pages I can't really show how pagination works.
https://kyrremann.no/hikari-for-jekyll/
https://github.com/Kyrremann/hikari-for-jekyll/settings

I had deleted the old repo, so had to make a new fork.

**Comment by Kyrremann** [comment]
Close this PR, see #49

**Pull request closed without merging**
